### ISSUE TITLE
GPU memory usage about this model

### ISSUE THREAD

**Issue by skywalkerzhang** [microsoft/Table-Pretraining#20]
Hi, I used 3090 to infer this model(hugging face version) on tabFact now(using test_examples.json file), and I found that my CUDA was out of memory(24G) for both batch inference and single inference. Could you please tell me how much memory I need to fine-tune this model so that I can apply for more instances? Thank you in advance!

**Comment by SivilTaram** [comment]
@skywalkerzhang Hi, thanks for your question! I think it is okay for inference on 24G memory since I use V100 (16G) for the inference lol. Maybe you can try to enable `fp16` to save memory?

**Comment by skywalkerzhang** [comment]
Thank you for your reply!!
I use 
```
       with torch.cuda.amp.autocast():
            outputs = model(**encoding)
```
but the memory cost seems larger. 

Here is my demo
```
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import pandas as pd
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
tokenizer = AutoTokenizer.from_pretrained(
    "microsoft/tapex-base-finetuned-tabfact")
model = AutoModelForSequenceClassification.from_pretrained(
    "microsoft/tapex-base-finetuned-tabfact")
model.to(device)

data = pd.read_csv("./tabfact_data/all_csv/2-13041602-6.html.csv", sep="#")
questions = [
    "there be only 2 day during august 2005 on which the brewer have a 50 / 50 win / loss record",
    "there be no day in august 2005 in which the brewer have a winning record",
    "the brewer lose in the game that have the biggest attendance in the month of august",
    "the brewer win the game which have the lowest attendance of the month",
    "there be only 4 day in august on which the brewer do not have to play a game",
    "there be only 3 day during august 2005 on which the brewer have a 50 / 50 win / loss record",
    "there be 3 day in august 2005 in which the brewer have a winning record",
    "the brewer win in the game that have the biggest attendance in the month of august",
    "the brewer lose the game which have the lowest attendance of the month",
    "there be only 3 day in august on which the brewer do not have to play a game",
]

encoding = tokenizer(data.astype(str),
                     questions,
                     padding=True,
                     return_tensors="pt",
                     truncation=True,
                     max_length=1024).to(device)

# let the model generate an answer autoregressively
with torch.cuda.amp.autocast():
    outputs = model(**encoding)

print(torch.cuda.memory_allocated(device) / 1024 / 1024 / 1024)

# decode back to text
predicted_class_idx = outputs.logits.argmax(dim=-1)
predictions = predicted_class_idx.cpu().detach().tolist()
print(predictions)
```
If I choose to turn on fp 16, the memory usage will be 17.51981782913208, and if I turn off fp 16, the memory usage will be 16.55494260787964. Moreover, if use a loop to infer all the data in the test set, the CUDA is just out of memory for this data. Could you please give me some advice about this? Thank you so much!

**Comment by SivilTaram** [comment]
@skywalkerzhang I am not really sure if amp can save memory. I usually use NVIDIA's `apex` to save memory consumption and it works fine! What will happen if you reduce the size of questions here? For example, leaving just one question?

**Comment by skywalkerzhang** [comment]
Are you using batch inference when doing experiments? I am not sure if my code has some problems. I cannot infer even a single question, but I am not sure if it is my code's problems or hugging face problems.

**Comment by SivilTaram** [comment]
@skywalkerzhang Yes, I use batch inference. But for huggingface models, the inference batch size is relatively small. You can find the eval script [here](https://github.com/huggingface/transformers/tree/main/examples/research_projects/tapex), which shows that:
```shell
export EXP_NAME=tabfact_tapex_base_eval

python run_tabfact_with_tapex.py \
  --do_eval \
  --model_name_or_path microsoft/tapex-base-finetuned-tabfact \
  --output_dir $EXP_NAME \
  --per_device_eval_batch_size 12 \
  --eval_accumulation_steps 6
```

I think it should be okay for your case using `tapex-based-finetuned-tabfact` since I have tested the script on V100 (16GB), but maybe because I have installed NVIDIA `apex`. I would recommend you to use the provided script and turn the `per_device_eval_batch_size` to `10` or lower.

**Comment by SivilTaram** [comment]
@skywalkerzhang And yes, the out-of-memory issue seems very strange because it is only a `base` model... I may try to reproduce it on my local GPU card in these days. But you can also try the provided script to do the evaluation. Or you can try the `eval` mode in this repo.

**Comment by skywalkerzhang** [comment]
Thanks for your reply. Another thing is, would you mind sharing the memory cost for the training step?

**Comment by skywalkerzhang** [comment]
I solved this problem. Sorry, it is my fault. I thought if I used hugging face then I don't have to use no grad...

**Comment by SivilTaram** [comment]
> Thanks for your reply. Another thing is, would you mind sharing the memory cost for the training step?

Sure. Typically the `per_device_train_batch_size` is `3` on table fact verification tasks with `24GB` memory. With `fp16`, you may have a larger batch size! See [here](https://github.com/huggingface/transformers/tree/main/examples/research_projects/tapex#tapex-base-on-tabfact) for more details.
